### PR TITLE
Remove broken and unused registration page, MISC-423

### PR DESCRIPTION
**Pull request by guilgaly**
Motivation:

- Registration page is broken (because the 'user' object is not initialized to an empty user when showing the form).
- Registration page isn't used in the academy course (and would do nothing since this demo app is immutable).

Modifications:

Remove the registration page and links leading to it.

Result:

No more registration page.

### CODE REVIEW

**Comment by guilgaly** [comment]
Note: alternately, we could keep the registration page and properly initialize the object used in the form, it's just one line of code. But the registration form wouldn't actually do anything, so probably more confusing than useful. On the login page, we do show the hardcoded test accounts which can be used.

**Review by Isammoc — CHANGES_REQUESTED** [review]
Even if the registration does not work.
We want to let that in place!

Purpose: let the user test a post request.

* Errors on password differences (weird this is backend)
* Other errors (mandatory fields)
* manage redirection on success

It's wanted that there is no real registration (would need moderation and we don't want to)

**Comment by slandelle** [comment]
Is this registration form:
* required and missing for the existing GA videos?
* necessary for a feature that’s not currently demoed in the existing GA trainings and that should be implementing along with re-shooting / updating the existing videos

**Comment by guilgaly** [comment]
For now I have opened pull request #11 to at least fix the form, then we can still discuss whether it should be kept at all.

**Review by tpetillot — COMMENTED** [review]
What's the state of this? Do we keep the page or not? 😸

**Comment by guilgaly** [comment]
From what I can see:
- This form isn't currently used in the Gatling Academy module.
- I don't think we would add anything of value to the module by adding a registration step: we already have a login step, which shows a similar form submission.

Then again, there's nothing _wrong_ with this form after the fix in #11, so I'd say we can just leave it in anyway?

**Comment by slandelle** [comment]
No. Let's remove. Unused + yet another way to increase session memory footprint.

**Review by slandelle — APPROVED** [review]

**Pull request merged**
